{% set version = "1.0-beta" %}
{% set sha256 = "57aa06f6ecaaa088419b51abc68b86d67142d89365b33e410f807518bfcb2413" %}

package:
  name: plasmar
  version: '{{version}}'

source:
  url: https://github.com/rastanton/PLASMAR/archive/v{{version}}.tar.gz
  sha256: '{{sha256}}'

build:
  noarch: generic
  number: 0

requirements:
  run:
    - python >=3.11
    - gamma
    - numpy >=1.25
    - scikit-learn =1.6.1
    - entrez-direct
    
test:
  commands:
    - GAMMA.py -h

about:
  home: https://https://github.com/rastanton/PLASMAR
  license: Apache License 2.0
  license_family: APACHE 
  summary: Plasmid Like Assembly Sequence Matching Algorithm for Resistance (PLASMAR)